services:
  fp-web:
    image: ghcr.io/xsaveopt/fp-web:latest
    container_name: fp-web
    restart: unless-stopped
    environment:
      ALLOWED_DOMAIN: ''
    ports:
      - '8080:8080'
    read_only: true
    tmpfs:
      - /config
      - /data
